# Base configs
baseurl: "https://saidorrois.github.io/ict3/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Digital Yearbook"
subtitle: "School Year 2022-2023"
author: "saio"
header:
 title: "ICT3 11-2 Yearbook"
 subtitle: "by company 🤓"
footer:
 name: "Made with ❤️ by"
 bio: "Bungay / Chiu / Lagura / Reyes / Sevilla A. / Sevilla F."
 github: "Digital Yearbook Project for ICT3 11-2 '22 '23 | Sir Santos / Sir Pakit"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
